### ISSUE TITLE
MIRA running on server no Download or Upload of sample sheet

### ISSUE THREAD

**Issue by ggonnella** [CDCgov/MIRA#77]
Dear developers,

we installed MIRA on our Ubuntu server, which we access remotely, "docker compose up -d" starts the docker correctly, as we can see from "docker ps". The only change we made in the docker-compose.yml is that we changed to port 8080, since our firewall blocks lower ports.

When we access the website using https://servername:8080, we can see the correct user interface. However, the button "Download Samplesheet Template" is not functional. Also when we select a file (a manually written samplesheet in XLSX for the tiny_test_run_flu example data - formatted according to the example in your documentation), the interface keeps re-opening the file selection dialog again and again.

Do you have any idea, what can be wrong, which could help us getting the installation work?

**Comment by kristinelacek** [comment]
Dear Giorgio,

Congratulations on your successful install of MIRA!

 The download samplesheet button will only work when the data is organized as the application expects. Can you share where you have saved the test data and how that is organized? Can you also check to see if your browser is blocking downloads from MIRA? We have observed that as well to be a cause of download failure.

Please feel free to email us at ***@***.***

Sincerely,
Kristine


________________________________
From: Giorgio Gonnella ***@***.***>
Sent: Monday, June 24, 2024 4:20 AM
To: CDCgov/MIRA ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [CDCgov/MIRA] MIRA running on server no Download or Upload of sample sheet (Issue #77)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.
________________________________


Dear developers,

we installed MIRA on our Ubuntu server, which we access remotely, "docker compose up -d" starts the docker correctly, as we can see from "docker ps". The only change we made in the docker-compose.yml is that we changed to port 8080, since our firewall blocks lower ports.

When we access the website using https://:8080, we can see the correct user interface. However, the button "Download Samplesheet Template" is not functional. Also when we select a file (a manually written samplesheet in XLSX for the tiny_test_run_flu example data - formatted according to the example in your documentation), the interface keeps re-opening the file selection dialog again and again.

Do you have any idea, what can be wrong, which could help us getting the installation work?

**Comment by ggonnella** [comment]
Sure: this is how the data is organized:

```
~/FLU_SC2_SEQUENCING$ ls tiny_test_run_flu/ -R
tiny_test_run_flu/:
fastq_pass

tiny_test_run_flu/fastq_pass:
barcode27  barcode37  barcode41

tiny_test_run_flu/fastq_pass/barcode27:
AMx369_pass_barcode27_143deb51_0.fastq.gz
AMx369_pass_barcode27_143deb51_1.fastq.gz
AMx369_pass_barcode27_143deb51_2.fastq.gz
AMx369_pass_barcode27_143deb51_3.fastq.gz
AMx369_pass_barcode27_143deb51_4.fastq.gz
AMx369_pass_barcode27_143deb51_5.fastq.gz
AMx369_pass_barcode27_143deb51_6.fastq.gz
AMx369_pass_barcode27_143deb51_7.fastq.gz
AMx369_pass_barcode27_143deb51_8.fastq.gz
AMx369_pass_barcode27_143deb51_9.fastq.gz

tiny_test_run_flu/fastq_pass/barcode37:
FAS60045_pass_barcode37_48aff321_0.fastq.gz

tiny_test_run_flu/fastq_pass/barcode41:
FAS60045_pass_barcode41_48aff321_0.fastq.gz
FAS60045_pass_barcode41_48aff321_1.fastq.gz
FAS60045_pass_barcode41_48aff321_2.fastq.gz

```

And this is the content of the spreadsheet:
```
Barcode #   Sample ID  Sample Type
barcode27  Sample27  Test
barcode37  Sample37  Test
barcode41  Sample41  Test
```

**Comment by kristinelacek** [comment]
Can you try to save your manually-made xslx as "samplesheet.csv" and put it in the tiny_test_run_flu folder? Hopefully you will see the table populate in the MIRA application afterwards.


Barcode #,Sample ID,Sample Type
barcode27,Sample27,Test
barcode37,Sample37,Test
barcode41,Sample41,Test

-Kristine
________________________________

**Comment by ggonnella** [comment]
We did that, but unfortunately no results. I.e. the MIRA application still does not see it.

```
~/FLU_SC2_SEQUENCING/tiny_test_run_flu$ cat samplesheet.csv 
Barcode #,Sample ID,Sample Type
barcode27,Sample27,Test
barcode37,Sample37,Test
barcode41,Sample41,Test
```

Other things we tried:
- the sys admins started the docker compose with "sudo", but it did not change things.
- I tried accessing the webapp on Konqueror, Google Chrome and Firefox. On Chrome I added all permissions I could set using the form for the website.

**Comment by kristinelacek** [comment]
Thank you Giorgio,
This is curious, we haven't experienced this behavior from MIRA yet. Could you please email to us the .appout and .apperr files that should be getting written within FLU_SC2_SEQUENCING folder?

Email address is ID seq support @ cdc.gov (I added spaces so it isn't redacted by github)

Again, that is idseqsupport @ cdc.gov (without spaces)

Thank you for your diligence here helping to troubleshoot.

Best,
Kristine
________________________________

**Comment by ggonnella** [comment]
email is out.

thank you for your troubleshooting support!

**Comment by kristinelacek** [comment]
Thanks for emailing us! If you need further help please feel free to email [idseqsupport@cdc.gov](mailto:idseqsupport@cdc.gov)

[MIRA v2.0.0](https://cdcgov.github.io/MIRA/articles/upgrading-mira.html) was released today and has an optional CLI-only module if that would better fit your needs!
