### ISSUE TITLE
MIRA MAC issues

### ISSUE THREAD

**Issue by jurresiegers** [CDCgov/MIRA#78]
Hi there,

I tried running MIRA through docker on my MacBook pro 2019 (intel chip).

I encountered the following errors:

1. When trying to execute the command `sudo docker-compose up -d` I get the error `WARN[0000] /Users/XXXXXXX/FLU_SC2_SEQUENCING/docker-compose.yml: version is obsolete`. I fixed this error by removing the version: 'x.x' line from your docker-compose.yml file.
2. The next error after rerunning `sudo docker-compose up -d` was `error getting credentials - err: exit status 1, out:`. This issue was fixing using `sudo chown -R $(id -u):$(id -g) $HOME/.docker` from https://forums.docker.com/t/error-failed-to-solve-error-getting-credentials-err-exit-status-1-out/136124/4.
3. The next error after rerunning  `sudo docker-compose up -d` was `must use ASL logging (which requires CGO) if running as root`. This issue was fixed simple by running the command as a non-root user `docker-compose up --build`.
4. After this the pull in my terminal/dock was successful however when I tried to run the example data (tiny_test_runs, I had to create my own sample sheet as the template wouldn't download) IRMA failed with the following message "Run has failed.  If you need further help, please contact us at IDSeqsupport@cdc.gov".

Best,
Jurre

**Comment by kristinelacek** [comment]
Dear Jurre,

Thank you for this detailed error report! Could you please email us at that provided email address (IDseqsupport) so we can do some thorough collaborative debugging?

Thank you!
Kristine
________________________________
From: jurresiegers ***@***.***>
Sent: Wednesday, June 26, 2024 12:04 AM
To: CDCgov/MIRA ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [CDCgov/MIRA] MIRA MAC issues (Issue #78)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.
________________________________


Hi there,

I tried running MIRA through docker on my MacBook pro 2019 (intel chip).

I encountered the following errors:

  1.  When trying to execute the command sudo docker-compose up -d I get the error WARN[0000] /Users/XXXXXXX/FLU_SC2_SEQUENCING/docker-compose.yml: version is obsolete. I fixed this error by removing the version: 'x.x' line from your docker-compose.yml file.
  2.  The next error after rerunning sudo docker-compose up -d was error getting credentials - err: exit status 1, out:. This issue was fixing using sudo chown -R $(id -u):$(id -g) $HOME/.docker from https://forums.docker.com/t/error-failed-to-solve-error-getting-credentials-err-exit-status-1-out/136124/4.
  3.  The next error after rerunning sudo docker-compose up -d was must use ASL logging (which requires CGO) if running as root. This issue was fixed simple by running the command as a non-root user docker-compose up --build.
  4.  After this the pull in my terminal/dock was successful however when I tried to run the example data (tiny_test_runs, I had to create my own sample sheet as the template wouldn't download) IRMA failed with the following message "Run has failed. If you need further help, please contact us at ***@***.******@***.***>".

Best,
Jurre

**Comment by kristinelacek** [comment]
Thanks for emailing us! If you need further help please feel free to email [idseqsupport@cdc.gov](mailto:idseqsupport@cdc.gov)

[MIRA v2.0.0](https://cdcgov.github.io/MIRA/articles/upgrading-mira.html) was released today and has an optional CLI-only module if that would better fit your needs!
